#!/bin/bash

# Opens the default log file with current editor. Accepts the standard
# `date -d` offset as arguments. Prompts to `git commit -m "New log
# entry."`. Resolves the editor to be used as follow:
# 
#    1. `$(kn Editor)`
#    2. `$EDITOR`
#    3. `vim`

relpath=$(kn datepath "$*")
dir="${KN}/log/$relpath"
file="$dir/README.md"
mkdir -p "${dir}"

"$EDITOR" +3 "${file}"

read -p 'Do you want to commit? ' commit

if [[ ! $commit =~ ^[Yy] ]]; then
  exit
fi

cd "${dir}"
git add "${file}" 
git commit
git push
