#!/usr/bin/perl
use v5.10; use strict; use warnings;

say 'Would render';

__END__

_render () {
  local error style
  local node="${1%/README.md}"
  local template='--template=main'
  local in="${node}/README.md"
  local hi='--no-highlight'
  local out="--output=${node}/index.html"
  local ddir="${README}/assets"
  [[ ! -e "${in}" ]] && _fail "Could not find ${CYAN} '${in}'"
  [[ -e "${README}/global.yml" ]] && gdata="global.yml"
  [[ -e "${node}/styles.css" ]] && style="--metadata=xstyles:styles.css"
  [[ -e "${node}/template.html" ]] && template="--template=${node}/template.html"
  error=$(pandoc -s -M title=_ ${nosyn} --data-dir=${ddir} ${hi} ${out} \
    ${template} ${style} ${gdata} ${in} 2>&1)
  [[ -n "${error}" ]] && echo ${CYAN}${node}:${RED} ${error}${RESET} >&2
}
